name: wfc

services:
  postgres:
    image: postgres:latest
    container_name: wfc-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Todo123!
      POSTGRES_DB: wfc_app
    ports:
      - "5434:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: wfc-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: wfcminio
      MINIO_ROOT_PASSWORD: wfcminio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./.data/minio:/data
